### ISSUE TITLE
One of our fonts may become fully italicized on latest Safari tech preview release?

### ISSUE THREAD

**Issue by bitprophet** [bitprophet/alabaster#100]
> [@hynek] Nice, the alabaster theme is broken in Safari TP (and Safari *TP* *only*). http://attrs.readthedocs.io/en/latest/ is all italics to me. cc @bitprophet
> ...
> running  Release 26 (Safari 10.2, WebKit 12604.1.12)

> [@jgelens] hmm looks fine here, using the latest TP
> ...
> I don't have these fonts though, maybe it's with that? "'goudy old style', 'minion pro', 'bell mt'"

> [@hynek] that’s my suspicion too.  I’ve just checked, http://www.python-requests.org/en/master/ looks broken too. 🎉  Thanks Apple!
> ...
> yeah it’s something with goudy old style.  removing it makes it look fine

----

So tl;dr if this isn't some odd TP-only bug that'll get fixed before release, Apple may have switched up fonts somehow, e.g.:

- the font-face normally selected by Safari on Hynek's Mac is now italic by default when it wasn't before
- Safari is now choosing a different font-face from our list than it used to - one that would have appeared as italics beforehand.
    - Which could possibly be the same as what Kenneth references in this comment: https://github.com/bitprophet/alabaster/issues/73#issuecomment-188608656 ?
    - Italics isn't the same as "really thin" but it's close enough to make me suspicious that the font just generally doesn't look good, assuming we find Hynek's Safari was not choosing Goudy before.

**Comment by hynek** [comment]
I’m 99.9% this is a TP bug that goes away in the next release.  I only linked you for your amusement about how terrible computers are.

**Comment by bitprophet** [comment]
Always good to have it on the record tho :D esp since this theme is more widespread now so you may well not be the only person to notice. But yea gonna close this so I don't forget to...can reopen if it persists.

**Comment by kennethreitz** [comment]
i'm on the latest beta release (not webkit nightly) and don't have any issues, fwiw

**Comment by hynek** [comment]
For posterity:

![2017-03-24 at 17 58](https://cloud.githubusercontent.com/assets/41240/24304951/88291afc-10bb-11e7-87c7-31f6e22e0a61.png)

on macOS 10.12.3 (16D32).

Empty caches and all extensions disabled.

**Comment by deanishe** [comment]
Now in Safari 11 😞 

![stupid-safari](https://user-images.githubusercontent.com/747913/30882477-5eca4614-a309-11e7-8e51-49f8ca9f88a9.png)

I just downloaded the repo and tried it on a local project. Stupid Safari.

**Comment by kennethreitz** [comment]
Not on my machine!

**Comment by deanishe** [comment]
I'm using Safari 11 on Sierra. What about you, @kennethreitz?

**Comment by hynek** [comment]
Yeah all alabaster sites look like that for me too.

It’s something with the Goudy Old Mill font because once you change it to say Palatino, everything looks fine: http://www.attrs.org/en/stable/

**Comment by kennethreitz** [comment]
I'm on High Sierra.

**Comment by hynek** [comment]
Ken, didn’t you mention in #73 that you always see Georgia anyways?  The italicization is specific to goudy old style.

**Comment by kennethreitz** [comment]
I trust your insight, @hynek :)

**Comment by hynek** [comment]
Well, I “solved” the problem for me by disabling goudy on my whole system. :)
