### ISSUE TITLE
Use literal block without code formatting?

### ISSUE THREAD

**Issue by Gabriel-p** [bitprophet/alabaster#102]
I'm trying to use a [literal block](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#literal-blocks) like:

```
dfsdlf dsflldfjlksdf dslfjksd flskdjf sdl

::

  some text in this line
  more text here

```
 
but the result is highlighted inside the block as if it were code, instead of just plain text (notice the `for`, `or`, `in`, and `is`):

![captura realizada el 2017-04-12 21 03 23](https://cloud.githubusercontent.com/assets/6054951/24984399/7fa9e110-1fc3-11e7-81f0-eb40fb992892.png)

[Here](http://photpy.readthedocs.io/en/latest/get_started.html#input) is the live example.

How can I use the block showing just plain text?

**Comment by bitprophet** [comment]
Pretty sure this is a generic Sphinx thing, all such blocks are considered code blocks and are highlighted as Python by default. Believe you can work around it by explicitly denoting it as a highlight of `none`, as per http://www.sphinx-doc.org/en/stable/markup/code.html

EDIT: yup, just tested with a copy of your source file and simply changing from:

```
::
```
to:

```
.. code-block:: none
```

Makes it stop treating the snippet like Python.

**Comment by Gabriel-p** [comment]
Thank you!
