### ISSUE TITLE
0.7.10 not available as release

### ISSUE THREAD

**Issue by fabaff** [bitprophet/alabaster#103]
It seems that 0.7.10 is not available for download at [Releases](https://github.com/bitprophet/alabaster/releases). Would be nice if you make a tarball available. Thanks.

**Comment by bitprophet** [comment]
Thanks for noticing! 0.7.10 seems to have been a confused release, the commit msg even says "0.8.0" instead of "0.7.10" (I probably changed my mind re: bumping minor version, due to Sphinx's dependency listing?)

Just tagged the release's commit & pushed the tag, and I see a tarball now. ✨
