### ISSUE TITLE
Remove Gratipay Options

### ISSUE THREAD

**Issue by HelloMelanieC** [bitprophet/alabaster#131]
Gratipay no longer exists :(

Proposed solutions: 
1. Remove the entire `donate.html` file and related code
2. Change this feature to use [Patreon](https://www.patreon.com/)
3. Change this feature to use [Stripe donations](https://stripe.com/)
4. Change this feature to use [Podia](https://www.podia.com/)

**Comment by bitprophet** [comment]
Duplicate of https://github.com/bitprophet/alabaster/pull/128! Which is still open! I have work to do.
