### ISSUE TITLE
Add Support/Donation Options

### ISSUE THREAD

**Issue by HelloMelanieC** [bitprophet/alabaster#132]
Add support to accept donations and/or financial support. 

**Suggested options:** 
1. [Patreon](https://www.patreon.com/)
2. [Stripe donations](https://stripe.com/)
3. [Podia](https://www.podia.com/)

**Steps:** 
- [ ] Add donate.html
- [ ] Add `donate.html` to the `html_sidebars` in /docs/conf.py
- [ ] Add notes for how to use the donate feature in /docs/customization.rst 
- [ ] Add notes for how to use the donate feature in /docs/installation.rst 

Note: see previous implementations of Gratipay support for a starting point

**Comment by bitprophet** [comment]
An aside to readers: this is a follow-on from #128 which removes Gratipay/Gittip for the time being (as that specific donation endpoint is defunct). That patchset is a good (reverse) guide for the above checklist.

**Comment by bitprophet** [comment]
Let's say that #143 handles this for now; future incremental changes (baked-in support for additional specific donation sites, like the list above) can be their own tickets. Will still remark on this issue number in the changelog 👍
