### ISSUE TITLE
Change Sphinx version in dev-requirements.txt

### ISSUE THREAD

**Issue by HelloMelanieC** [bitprophet/alabaster#133]
The following error is received upon install: 

> releases 1.5.0 has requirement sphinx<1.7,>=1.3, but you'll have sphinx 1.7.4 which is incompatible.

Need to add a more specific requirement for Sphinx.

**Comment by bitprophet** [comment]
Thanks for surfacing this!

Side note: the reason Releases doesn't like Sphinx 1.7+ is that version breaks Releases :( we'll work around that eventually on that end...

Github should autoclose this shortly.
