### ISSUE TITLE
Configuring the favicon

### ISSUE THREAD

**Issue by shreyasbapat** [bitprophet/alabaster#138]
Can we configure the favicon as well using this theme? 
I could not find anything in the documentation.

**Comment by bitprophet** [comment]
As far as I know the Sphinx setting for that should work fine, I don't think themes really touch favicons? http://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_favicon

If you find that I'm wrong and the theme needs to do something to assist, please comment and we can reopen! Thanks :)

**Comment by shreyasbapat** [comment]
Yes, I am sorry for the unwanted issue! Thankyou for your quick reply!
I have some queries, I know this is not a proper thread for doing that.
If we fix the side bar, is there any way we can collapse the menu in the mobile view?
