### ISSUE TITLE
Search appends suffix "txt" to every search path incorrectly

### ISSUE THREAD

**Issue by jmckenna** [bitprophet/alabaster#155]
### Problem

(seems somewhat similar to https://github.com/rtfd/sphinx_rtd_theme/pull/346)

Search appends "txt" to every filename, causing a 404 error.

````
404 (not found) /_sources/myfolder/filename.txt.txt
````

..where the correct file is named "filename.txt"

### Versions Affected

- this problem has existed since Sphinx 1.5.0 (Sphinx 1.4.9 works fine)
- problem exists with: 
  - Sphinx 2.0.0, 1.8.1 or 1.7.6, and alabaster 0.7.*  etc.

### How to Reproduce

Actually you can see it live: https://mapserver.org/search.html  

(that is a Travis instance, Python 3.7.1, alabaster 0.7.12, Sphinx 2.0.0)

### Initial Report

I initially reported this on Sphinx github back in 2016, and I wrongly assumed I was using the sphinx_rtd_theme, but I was using the Alabaster theme all this time: https://github.com/sphinx-doc/sphinx/issues/3250

### Environment Info

- Python Version: 3.7.1
- Sphinx Version: 2.0.0
- Alabaster 0.7.12

**Comment by tk0miya** [comment]
It seems your searchtools.js is too old. Its copyright says "2007-2010". It's not Sphinx-2.0's.
https://mapserver.org/_static/searchtools.js

I don't know why you're using old js file. But this is not related with both alabaster theme and Sphinx itself. Please full rebuild your document and upload it.

**Comment by jmckenna** [comment]
@tk0miya I finally solved the issue.  You were right, there were 5 very old files including searchtools.js inside the _static folder, which would overwrite the generated ones in _build/html/_static/       Yikes!    Thank you for your advice here it really helped.  I am sorry to file so many tickets.  Thank you again though!  mapserver.org is a longtime Sphinx site.  Thank you.
