### ISSUE TITLE
Is this project no longer maintained?

### ISSUE THREAD

**Issue by asmeurer** [bitprophet/alabaster#177]
The most recent commit on this repository (from January 2020) says "Last ever LICENSE copyright update". https://github.com/bitprophet/alabaster/commit/3b68afcfe55a80508254b22904294100a160e6a7

Does that mean that you no longer intend to maintain this project any more, or am I misunderstanding the meaning of that commit message? I don't see any other indication that that's the case. The lack of activity over the past year is also concerning, but if that's just because you haven't had time I understand that. 

If it is the case that you no longer want to maintain this, I wonder if it would make sense to move this repository into the [sphinx-doc](https://github.com/sphinx-doc) user space, or into Sphinx itself, given that it is a hard dependency and the default theme for new Sphinx projects. I apologize if any of this has already been discussed before. I couldn't find any prior discussions.

**Comment by bitprophet** [comment]
No, that was extremely poor language choice on my part, intended to reflect that I'm just done with the annual copyright update (it's just not legally necessary). I haven't had time to focus on this repo in some time but it's not abandoned. I HAVE been meaning to discuss altering ownership with the Sphinx team at some point and that will happen at some point for sure.

Thanks for asking!

**Comment by asmeurer** [comment]
OK thanks for answering. I would love to see ownership moved if that would lead to better maintenance. I really like this theme, and would hate to see it go by the wayside.

**Comment by AA-Turner** [comment]
@bitprophet -- would you be open to transferring the repo to @sphinx-doc so that the Sphinx team can also update it?

A

**Comment by bitprophet** [comment]
@AA-Turner That sounds like a great idea! I'll look at doing that once the dust settles on some inflight stuff in my other projects. I may take a final whack at it on my end and do some of the administrative updates I'm doing elsewhere - drop Python 2 support, move CI (basic as it is) to Circle-CI, etc. During that sort of shakeup, transferring it to sphinx-doc org should work well as part & parcel.

**Comment by AA-Turner** [comment]
Very happy to tackle the admin if you'd like! Could you add me as an admin to this project in the meantime? My GH username and PyPI usernames are both AA-Turner.

Thanks!

A

**Comment by bitprophet** [comment]
Invitations sent on both! Re: admin: if you look at recent commits I've made to eg https://github.com/bitprophet/releases / https://github.com/bitprophet/pytest-relaxed / https://github.com/pyinvoke/invocations, you'll see the kinds of things I mean - nuking support for Python <3.6 and everything else that entails; readme tweaks; a .circleci/config.yml (I might need to twiddle something on their end for that to work 100%, until the repo gets moved).

**Comment by AA-Turner** [comment]
@bitprophet 

> drop Python 2 support

Done

> Move CI (basic as it is) to Circle-CI

Done; moved to GitHub Actions for integration with the UI.

> readme tweaks

Wasn't sure what you envisaged here.

Please let me know when you put the transfer request to @sphinx-doc through!

A

**Comment by asmeurer** [comment]
I would suggest including a screenshot in the README.

**Comment by bitprophet** [comment]
See some comments I left under #195 / #196 / #197, @AA-Turner - had a branch snafu but also had some other unrelated changes to put in, and release. Will be trying to push out 0.7.13 very shortly, then back to the "let's move it over to the org & I take my hands mostly off the wheel" plan.

@asmeurer That's a good idea but suspect it belongs in its own ticket!

**Comment by not-my-profile** [comment]
It's nice to have some activity again in alabaster, however the deletion of the `master` branch (in the process of switching to `main`) has closed all the pull requests that were open, which were dozens that have all been left unanswered for years prior.

I just reopened my PR #198 to fix the width issue from 2018 but I assume that the other PRs will remain closed ... it would be nice if someone could at least merge the commits from the PRs I listed in https://github.com/sphinx-doc/sphinx/issues/10145.

**Comment by bitprophet** [comment]
@AA-Turner It looks like I can't initiate the transfer to the Sphinx org myself, as I lack repo create permissions there. I'm also guessing you can't do it as you're a collab here but not an owner (as it's a personal repo). Can you confirm this?

Assuming I'm right, then figure one of:

a) I get added briefly over on Sphinx w/ repo create, transfer, and then my privs get revoked (or at least limited to the transferred alabaster repo);

or b) we launder the repo through an org I create for that purpose, as I could then add you to that org as an admin and you'd gain transfer permissions that way (though this seems likely to be more frustrating for users, and I'm not even positive that watchers/forks/etc would survive such a double-transition, though I think they ought to).

**Comment by AA-Turner** [comment]
Thanks for the update, I've added you to the @sphinx-doc organisation, that should enable the transfer. I'll then move you just to ``sphinx-doc/alabaster`` afterwards.

A

**Comment by bitprophet** [comment]
@AA-Turner - just transferred! and confirming via this comment that the redirect is functioning 🎉

**Comment by bitprophet** [comment]
- Already added Adam to PyPI a while back
- Confirmed that CircleCI automatically updated with the transfer
- Just pushed a commit to the new git remote location which updates all the old URLs etc that I could turn up: https://github.com/sphinx-doc/alabaster/commit/f0cb3194610b8a6d17571d49b6aa8ca8b1edde8a
- Will check up on Codecov (likely auto-updated too as IIRC that's using GH auth) and RTD (will prob need to add Adam to RTD as I did for PyPI) next

**Comment by bitprophet** [comment]
![image](https://user-images.githubusercontent.com/6088/222978415-1bc7fc4c-8c11-47ae-92d4-db63194da3be.png)

Something for @AA-Turner or another actual Sphinx admin to think about. That's an orb I authored which lives in the Invoke GH org.

**Comment by bitprophet** [comment]
Aside from having my perms tightened back down to just Alabaster, getting CI working again per above, and sorting out Tidelift, this is done! Excited to see where things go from here.
