### ISSUE TITLE
img.align-center should have a max-width:100%

### ISSUE THREAD

**Issue by emptymalei** [bitprophet/alabaster#20]
to prevent the image from exceeding the page width?

or probably img max-width ?

**Comment by bitprophet** [comment]
Do you have a good example of this in practice (i.e. where a big image is breaking things)?

**Comment by emptymalei** [comment]
I fixed it by using a customized style.css. This problem appears as I insert an image using the following `rst` code,

```
.. figure:: https://upload.wikimedia.org/wikipedia/commons/c/c4/Alcubierre.png
   :align: center
```

And the resulting HTML image would be using the actual image size so it exceeds the page width if the image is very large.

I am using

```
img {
	max-width:100%;
}
```

to prevent this from happening.

**Comment by bitprophet** [comment]
Hrm, when I add that figure to one of my doc pages and rebuild it, it's scaling down to whatever width my content box is.

When I inspect the element I see that my browser *is* applying `img { max-width: 100% }` and it's coming out of the Sphinx `basic` theme's CSS (which Alabaster inherits from). So this should be applying to any image by default as far as I can tell.

If you can dig around in your browser's inspect function to figure out what's going on, maybe something will come up, but for now I can't reproduce this :( sorry!
