### ISSUE TITLE
1.0.0 release incompatible with Sphinx 7.4.7 (latest)

### ISSUE THREAD

**Issue by jmckenna** [bitprophet/alabaster#220]
- filed upstream at: https://github.com/sphinx-doc/sphinx/issues/12693
- however, packagers will likely come here to the Alabaster repo, to find discsussions, so tracking here also

**Comment by AA-Turner** [comment]
Thanks Jeff, I've responded in https://github.com/sphinx-doc/sphinx/issues/12693.

A
