### ISSUE TITLE
[Feature Request] Improving the mobile layout

### ISSUE THREAD

**Issue by ghost** [bitprophet/alabaster#223]
Many modern Sphinx themes such as [Furo](https://pradyunsg.me/furo/), [Book](https://sphinx-book-theme.readthedocs.io/en/stable/), and [PyData](https://pydata-sphinx-theme.readthedocs.io/en/stable/) use a sidebar for mobile view. 

The problem is that when in mobile view, the "Sidebar" goes to the bottom of the page, which could be inconvenient for users who like using a sidebar to get around. It also removes the logo.  My suggestion is that for mobile view, there is a sidebar button, which brings up the grey sidebar, and also renders the logo. This would be helpful for easier navigation.

**Comment by AA-Turner** [comment]
See #44 and several other similar. PR welcome, though, if you would like to improve things.

A
