### ISSUE TITLE
Tabular Bibliography Entries

### ISSUE THREAD

**Issue by pdessus** [bitprophet/alabaster#27]
Dear Jeff,
congrats for your alabaster ext. I love it!
I encounter problems in changing the ugly border of the bibliography entries (generated by sphinx-contrib-bibtex): they appear by default in tables with 1px border and I haven't succeeded in putting it without border (but I need that regular tables to keep their border as well). 
This might be changed in the theme.conf file.
See end of this file: http://webcom.upmf-grenoble.fr/sciedu/pdessus/sapea/innovation.html
Thx for your help in advance!
best 
philippe

**Comment by bitprophet** [comment]
Hi @pdessus, has your published document changed in the last few days? I'm not seeing the tables you speak of. The page I load looks like this: https://www.evernote.com/shard/s215/sh/7ce3842a-8a65-43d4-b566-b6a9a75cd48c/f7e6daedc70b7e40/res/1f68bc66-2fd4-4a8a-9f47-d60f1bedcb70/skitch.png

I outlined in red an actual table, and then the output of the `.. bibliography::` directive, which looks relatively normal to me for a biblio format.

**Comment by pdessus** [comment]
hi Jeff,
this is the updated version with a css tweak inserted at the end of the alabaster css:

----ajout pour supprimer les bordures des refs-------------------------------*/
table.docutils.citation, table.docutils.citation td, table.docutils.citation th {
  border:none; /* pour la bordure */
  /*Début de gestion de l'ombrage discret*/
  -moz-box-shadow: none;
  -webkit-box-shadow: none;
  box-shadow: none;
  /*fin de gestion de l'ombrage*/  
without this one, the "docutils citation" css style displays ugly (and unusual) table borders (the same as those of Tables). Would it be possible to add this border modification directly in the theme.conf file?
best!
ph

**Comment by bitprophet** [comment]
[I edited your comment to add a code block for readability :)]

Thanks, I will try manually removing those styles and see if it makes your problem appear for me.

**Comment by pdessus** [comment]
dear Jeff,
FYI, a screenshot attached, showing the refs tab. borders (refs being created thru http://sphinxcontrib-bibtex.readthedocs.org/en/latest/)
![screendump](https://cloud.githubusercontent.com/assets/10684380/5933943/004463f8-a6c8-11e4-8c0c-1e0bfb1e925a.png)
best!
ph

**Comment by bitprophet** [comment]
@pdessus Yup, that's exactly what I saw when I tweaked your page using my browser's developer tools :) Once the next release of Alabaster goes out, the stylesheet should include this change. Thanks!

**Comment by pdessus** [comment]
cool, you got it! thanks for this beautiful theme;
best
ph

**Comment by pdessus** [comment]
Dear Jeff,
thanks for acknowledging me in the new version of Alabaster 0.7.1 ;-)
However, I have to tell you that the modification you did is not sufficient to remove all the borders (the shadow still remains), see attached.
thx for your help,
best!
ph
![capture d ecran 2015-03-14 a 19 00 36](https://cloud.githubusercontent.com/assets/10684380/6652834/147658d0-ca7d-11e4-9889-df415630de67.jpg)

**Comment by bitprophet** [comment]
Hi @pdessus - which exact browser & operating system are you on? My (recently updated) Chrome (on Mac OS X 10.10/Yosemite) doesn't display those shadows. Neither does Safari.

**Comment by pdessus** [comment]
hi Jeff,
I'm on Yosemite 10.10.2 and Safari 8.0.3, Sphinx 1.2.3.
best
ph

2015-03-17 22:29 GMT+01:00 Jeff Forcier <notifications@github.com>:

**Comment by bitprophet** [comment]
Yea, I'm not seeing it on 10.10.2 + Safari 8.0.4 (I was on 8.0.3 the other day, same deal).

To be specific, I am looking at http://webcom.upmf-grenoble.fr/sciedu/pdessus/sapea/innovation.html which was your earlier link.

Screenshot: ![](https://www.evernote.com/shard/s215/sh/83ff6cda-d867-4a55-bec6-9d8333260b61/a2b485827eb48bf6ff8dacfd137697f4/res/3d30be8b-fd72-496e-9ace-e5a998c1dbe8/skitch.png)

My Safari is not customized (Chrome is my main browser)...do you have any custom stylesheets or plugins on your end that could possibly be causing this difference?

Either way, if you can identify the style rule that is causing this (I looked in Chrome's inspector and did not see anything appearing as "active" that would be the culprit) we can take a look.

**Comment by pdessus** [comment]
dear Jeff,
indeed, but I tweaked again your alabaster.css_t file to have this
rendering;
these info has to be added in order to remove the shaded boxes (please try
it):
  /*Début de gestion de l'ombrage discret*/
  -moz-box-shadow: none;
  -webkit-box-shadow: none;
  box-shadow: none;
  /*fin de gestion de l'ombrage*/

thx!
ph


2015-03-18 22:57 GMT+01:00 Jeff Forcier <notifications@github.com>:

**Comment by bitprophet** [comment]
Yup, I'm being dumb and keep forgetting your live website has your own changes applied on top of the core stylesheet. When I use my inspector to remove `box-shadow: none`, I do see the shadow. I'll add these lines. Thanks!

**Comment by bitprophet** [comment]
0.7.3 is out with that change.

**Comment by pdessus** [comment]
Dear Jeff,
Thx to u for this awesome theme!
Best,
Ph
