### ISSUE TITLE
Upload wheels to pypi

### ISSUE THREAD

**Issue by aragilar** [bitprophet/alabaster#33]
Can you upload wheels of alabaster to pypi as per https://packaging.python.org/en/latest/distributing.html#wheels, as it makes alabaster faster to install.

**Comment by bitprophet** [comment]
Thanks for the note! +1, I have wheels working for one project (Paramiko) and need to get that love spread to the rest. (Also linting, etc). Basically just need to do what Paramiko's task file does, which is to call [this](https://github.com/pyinvoke/invocations/blob/b3e892f476c743a6ed2e2518fd1c9c2bec4d56ae/invocations/packaging.py#L155-L158), spread around to other projects like this one.

**Comment by SamWhited** [comment]
More specifically, a universal wheel (or a separate Python 3 wheel) would be much appreciated.

**Comment by bitprophet** [comment]
Thanks, will merge the PR when I get around to updating the release taskset to do wheels by default.

**Comment by bitprophet** [comment]
Seems like I did this at some point already, there's wheels on PyPI for the latest release & I've got a tasks.py pulling in the latest invocations release module (which defaults to both sdist and wheel).
