### ISSUE TITLE
Navigation isn't rendered

### ISSUE THREAD

**Issue by tpievila** [bitprophet/alabaster#35]
Not sure if this issue should go to sphinx itself, but the new recommendation to use alabaster in 1.3 causes some unexpected behavior with domains providing indices: the navigation div is not visible with alabaster, unlike in classic.

For example the [httpdomain](https://bitbucket.org/birkenfeld/sphinx-contrib/src/default/httpdomain/sphinxcontrib/httpdomain.py?at=default#cl-631) creates a routing table page, and links to it in the navigation div:

    <div class="related" role="navigation" aria-label="related navigation">
      <h3>Navigation</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="genindex.html" title="General Index"
             accesskey="I">index</a></li>
        <li class="right" >
          <a href="http-routingtable.html" title="HTTP Routing Table"
             >routing table</a> |</li>
      </ul>
    </div>

**Comment by bitprophet** [comment]
Thanks for the report! Could be a Sphinx bug but seems quite possible it's on our end.

Do you have links to a live example of this (ideally something with public sources I could clone & replicate the issue with)? I haven't used httpdomain before and generally don't look at indexes much either way (probably why this was not noticed before).

**Comment by tpievila** [comment]
For example http://docs.spate.io/en/latest/http-routingtable.html.

The generic index is a part of core sphinx and has (a link from the quickstart generated frontpage)[ http://sphinx-doc.org/markup/toctree.html?highlight=genindex#special-names]. But yes, they also can't be navigated from other pages without the nav div.

I dug a bit deeper and noticed that navigation _is_ rendered if the screen is narrow enough. Perhaps the sidebar is meant to replace it, but unfortunately it has different navigation links.

**Comment by bitprophet** [comment]
OK, I see what you mean now, and this triggers a memory, I removed the "related" nav quite some time ago as it didn't make sense for the sites I was using the early versions of this theme on. Clearly I didn't remove it entirely as it shows up in mobile-oriented responsive views.

Will poke at making it possible to enable this 100% via a setting - in the interests of backwards compat I will probably have it stay off by default for now.

**Comment by bitprophet** [comment]
Digging some more:

* The base theme which we inherit from has a `relbar` macro used in two blocks, `relbar1` above content and `relbar2` below content (thus why most pages in older Sphinx themes have these next/previous links at top/bottom of the page)
* Our theme, dating from the kennethreitz or mitsuhiko days, explicitly nixes the bottom `relbar` by defining an empty `relbar2` block but omitting any mention of `relbar1`. Indeed, this is what we see when the page is small enough to trigger mobile view.
* Sure enough, looking at our stylesheet, I updated `div.related` to be `display: none` in the broadly applied section, but neglected to touch the `max-width: 875px` section, which is the 'mobile' view.
* So should be able to use templatetags in both places to make them consistently visible & controllable.

**Comment by bitprophet** [comment]
OK, have that setting in and working. Naturally, the "new" element looks pretty terrible. Should probably revert part of that old commit so these nav elements appear in the sidebar instead? That seemed to make sense layout-wise and is what the source themes did, explicitly.

**Comment by bitprophet** [comment]
@tpievila OK, this is in master now, it adds a new element to the sidebar, see the tail end of the README.rst for details on how to enable it for an existing site - just update `html_sidebars` and your theme conf dict.

Please let me know if it works out for your use case - if it doesn't, I am open to alternative CSS/HTML suggestions (please be specific :D), though I do think this element type works best in the sidebar & it also keeps with the feel of the source themes (see e.g. non-index pages on Requests' docs such as http://docs.python-requests.org/en/latest/user/advanced/).

**Comment by tpievila** [comment]
This implements the links the basic theme has in the sidebar macro / relations.html template, but not the ones in the relbar macro, which has all of the indices. Something like https://github.com/bitprophet/alabaster/compare/master...tpievila:related?expand=1 is needed. If the intention is to leave this for user created templates, perhaps it could be added to docs?
