### ISSUE TITLE
Documentation for github_button on readme page  

### ISSUE THREAD

**Issue by maweigert** [bitprophet/alabaster#47]
Right now is says
```
github_button_type: Defaults to watch.
github_button_count: Defaults to true.
```
but should be
```
github_type: Defaults to watch.
github_count: Defaults to true.
```

**Comment by homeworkprod** [comment]
Slightly related: It seems to me that `github_button` is never used in the templates at all. A simple repo search on GitHub for that string seems to support that claim.

Did the GitHub "banner" (in the top right) replace the "button", or is it the new name for it?

**Comment by maweigert** [comment]
@homeworkprod It is used in about.html line 18 and it does as expected when using it.

**Comment by homeworkprod** [comment]
@maweigert, ah, indeed! It's prefixed, so maybe that's why the search didn't find it.

I did test it locally, but couldn't see any button. According to the template, it's in an iframe, so maybe some browser extension blocked it on `file://` by default.

Thanks for letting me know!
