### ISSUE TITLE
How do I enable a "Home" link in the alabaster theme

### ISSUE THREAD

**Issue by nikolas** [bitprophet/alabaster#49]
I have some documentation up here: http://django-pagetree.readthedocs.org/

How do I make the top left of the page be a link to the root of the documentation, with the title of the package (django-pagetree) instead of the text "This Page"?

The docs for the `logo` options state:

> If logo is not set, your project name setting (from the top level Sphinx config) will be used in a text header instead. This preserves a link back to your homepage from inner doc pages.

But that doesn't seem to be working for me.

**Comment by bitprophet** [comment]
Hm, I don't see anything obviously missing in your setup compared to e.g. http://paramiko.org whose conf.py is contained in https://github.com/paramiko/paramiko/blob/master/sites/www/conf.py and https://github.com/paramiko/paramiko/blob/master/sites/shared_conf.py - but maybe take a gander at those two files and see if you notice anything.

**Comment by nikolas** [comment]
I got it working, by defining `html_sidebars` like this:

```py
html_sidebars = {
    '**': [
        'about.html',
    ]
}
```

Maybe we should add this to the documentation.

**Comment by polyzen** [comment]
Sidebars are mentioned here: https://alabaster.readthedocs.io/en/latest/installation.html

**Comment by nikolas** [comment]
Cool thanks!
