### ISSUE TITLE
Changing font size for MathJax

### ISSUE THREAD

**Issue by solarjoe** [bitprophet/alabaster#76]
Hello,
sorry for posting to "Issues" but I could not find another location.

Is it possible to enlarge the font size of the the embedded equations
in Alabaster (or Sphinx in general)?

I only found `.MathJax {font-size: 1.3em;}` somewhere, but I am not
that familiar with CSS.

Kind regards,
Joe

**Comment by bitprophet** [comment]
A) I don't use equations myself so I don't know if that rule is truly the one you need, but it sounds likely to me. You should be able to confirm/deny it by using your browser's dev tools to twiddle the value of that rule & see if the rendered page updates the way you want.

B) Assuming that or other CSS rules will do the trick for you - I don't know that this merits its own config option but it prompted me to look into what became #78. I'll try to bang that out soon & it would let you add e.g. `_static/custom.css` to your docs folder, where you could override that or other CSS rules. Going to roll this into that ticket. thanks!

**Comment by bitprophet** [comment]
Oh and p.s. for general sphinx issues, there's a google groups linked on sphinx-doc.org: http://groups.google.com/group/sphinx-users
