### ISSUE TITLE
Including a link to genindex in the toctree

### ISSUE THREAD

**Issue by wood-chris** [bitprophet/alabaster#79]
(maybe this is a more general sphinx question, rather than alabaster specific?)

When you run `sphinx-quickstart`, it generates 3 links on the index page:

 - `:ref:genindex`
 - `:ref:modindex`
 - `:ref:search`

Alabaster allows you to add a search box in the html sidebar (`searchbox.html`), but when I try adding `genindex.html` nothing gets shown. I've tried adding `:ref\`genindex\`` to the `toctree` too, but that generates a warning of `WARNING: toctree contains reference to nonexisting document u':ref:/`genindex/``

Intriguingly, when I do _both_ of the above, I get an additional warning of `Recursion error: maximum recursion depth exceeded in cmp`.

One potential solution appears to be in [this Stackoverflow answer](http://stackoverflow.com/a/33340209/889604), but this would only add it as an additional link; I have actually managed to achieve this in an alternative way by adding `'Index' : 'genindex.html'` to the `'extra_nav_links'` dictionary - but this doesn't seem particularly elegant because it doesn't use the `:ref:` cross-referencing syntax

**Comment by bitprophet** [comment]
I don't habitually use those links, but I don't *think* those are intended to end up in the ToC?

I'm guessing this is kind of duplicating #43, which is the other open ticket re: the index/indices pages. Let's roll it into there.
