### ISSUE TITLE
Twitter account link in sidebar

### ISSUE THREAD

**Issue by lunaryorn** [bitprophet/alabaster#82]
Hello,

I'd like to add a Twitter account link to the side bar, right below the Github button.  How'd I do that? Which template do I need to edit?

**Comment by kennethreitz** [comment]
sidebarintro and sidebarlogo :)

You can see an example here: 
https://github.com/kennethreitz/requests/tree/master/docs/_templates

**Comment by kennethreitz** [comment]
I am using the Twitter button there (inspired by @myusuf3).

**Comment by bitprophet** [comment]
@kennethreitz / @myusuf3 - thoughts on whether this is worth adding to 'core' as an option (like the github button etc)? I'm leaning 'probably'.

**Comment by kennethreitz** [comment]
@bitprophet eh, it depends on the goal of the project (this project). If you want to promote people promoting their own personal brands, then yes.

**Comment by lunaryorn** [comment]
I'd not say that Twitter accounts necessarily relate to "personal brands".  At least, I didn't add my own account to the sidebar but the projects account which tweets about releases and breaking changes.

And likewise, a link to a GitHub repo under a personal user account promotes a personal brand, too, doesn't it?

**Comment by kennethreitz** [comment]
I think the primary use case would be personal accounts. Few projects have Twitter accounts. 

GitHub link is definitely personal promotion, albeit a little less shameful/blatant, since its directly related to code, as Twitter is typically not.

**Comment by myusuf3** [comment]
For whatever reason, I think its cool.
