### ISSUE TITLE
Admonitions are "outdented" and therefore look like they violate nesting.

### ISSUE THREAD

**Issue by inducer** [bitprophet/alabaster#85]
Using admonitions within, say, the indented bit of the documentation of a method looks to nest the wrong way because it "outdents" by 60px:

https://github.com/bitprophet/alabaster/blob/1c3393da3a99eb0ef3792b922866daf5559bcbf9/alabaster/static/alabaster.css_t#L279-L282

To me, the net effect is that the note appears to nest at the top level, and then the indented bit resumes, at an unclear level of nesting.

[Example](https://documen.tician.de/pyopencl/runtime_memory.html#pyopencl.SVM)

Just deleting the two highlighted lines above makes life better.

**Comment by bitprophet** [comment]
See #32, this has been a long-standing gripe for various elements. I don't think we had a specific note about admonitions though, mostly code blocks. Rolling into that issue - thanks for the report!
