### ISSUE TITLE
Logo theme variable does not seem to work?

### ISSUE THREAD

**Issue by tgoodlet** [bitprophet/alabaster#97]
I've tried a few different things at this point in terms of a [`$PROJECT/_static/` relative path](http://alabaster.readthedocs.io/en/latest/customization.html#variables-and-feature-toggles) but can't get an `img` tag to show up anywhere (this is after grepping html files of course).

It appears there is an [open question on stackoverflow](http://stackoverflow.com/questions/42034752/html-theme-options-vs-html-logo-in-conf-py-using-alabaster) by someone else who is having the exact same problem.

I've had to fall back to using a `html_logo = '_static/img/logo.png'` declaration for now.

Any help or suggestions that you can provide would be greatly appreciated :)

**Comment by chriscz** [comment]
This seems to be related to #86.

**Comment by chriscz** [comment]
I've looked at Alabaster's `conf.py` file and it specifes its own structure for the sidebar. 
So far this is the closest solution I have come to.
```python
html_sidebars = {
    '**': [
        'about.html',
        'navigation.html',
        'searchbox.html',
    ]}
```

You basically specify the structure of the sidebar yourself. Here `about.html` contains
the templates for `logo` and `logo_name`, hence if it is not included then it won't be displayed.

The [sphinx documentation](http://sphinx-doc.org/config.html#confval-html_sidebars) has more information on `html_sidebars`.

This is definitely a bug in alabaster.

**Comment by chriscz** [comment]
Ok, I've got a bit closer now to what I originally wanted. I've looked at `layout.html` of the original basic theme (which alabaster extends) and this setup is the closest to what the basic navigation bar looks like, but with the logo support working as expected.

```python
    html_sidebars = {
        '**': [
            'about.html',
            'localtoc.html',
            'relations.html',
            'sourcelink.html',
            'searchbox.html',
        ]
    }
```

**Comment by bitprophet** [comment]
Let's say this is part of #86, since it seems to be the same issue. Will post an update there. thanks!
