### ISSUE TITLE
Documentation on adding external links is not clear

### ISSUE THREAD

**Issue by ThePragmatist** [bitprophet/alabaster#98]
I was initially confused by this in cutomization.rst:

``extra_nav_links``: Dictionary mapping link names to link targets; these
   will be added in a UL below the main sidebar navigation (provided you've
   enabled ``navigation.html``.)

How about something like:

``extra_nav_links``: Dictionary mapping link names to link targets; these
   will be added in a UL below the main sidebar navigation (provided you
   enable ``navigation.html`` in the sidebar. This can be configured 
   using the ''html_sidebars'' option.)

Something like this would have given me a hint about how to turn this on. Instead there was much googling and looking at source code. Looking at navigation.html in the theme itself didn't help because it isn't referenced anywhere (because it is an optional thing). :)

I can create a pull request if you like, not sure if it is more work to do that than for someone else to just fold it into something else they are up to.

**Comment by bitprophet** [comment]
Thanks for the request for clarification, agree it assumes a lot for anyone not already intimate with Sphinx :) does that commit's change seem like it'd help?
